LORE_MARKER = "<<<LORE_BLOCK>>>"
CHARACTERS_MARKER = "<<<CHARACTERS>>>"

# common words to ignore
NAME_STOPWORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "the",
        "my",
        "your",
        "his",
        "her",
        "their",
        "our",
        "i",
        "me",
        "we",
        "you",
        "he",
        "she",
        "they",
        "it",
        "this",
        "that",
        "in",
        "at",
        "to",
        "from",
        "with",
        "for",
        "of",
        "by",
        "on",
        "and",
        "or",
        "but",
        "so",
        "if",
        "than",
        "then",
        "is",
        "was",
        "are",
        "were",
        "be",
        "been",
        "being",
        "have",
        "had",
        "do",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "here",
        "there",
        "when",
        "where",
        "what",
        "who",
        "how",
        "why",
        "old",
        "young",
        "big",
        "small",
        "new",
        "good",
        "bad",
        "just",
        "very",
        "well",
        "also",
        "back",
        "even",
        "still",
        "way",
        "look",
        "come",
        "want",
        "know",
        "think",
        "see",
        "get",
        "make",
        "said",
        "yes",
        "no",
        "not",
        "now",
        "up",
        "out",
        "okay",
        "ok",
        "hey",
        "oh",
        "ah",
        "hmm",
        "uh",
        "um",
    }
)

# relationship role words
RELATION_WORDS: frozenset[str] = frozenset(
    {
        "friend",
        "companion",
        "ally",
        "rival",
        "enemy",
        "brother",
        "sister",
        "mother",
        "father",
        "son",
        "daughter",
        "parent",
        "child",
        "husband",
        "wife",
        "partner",
        "spouse",
        "boyfriend",
        "girlfriend",
        "fiance",
        "fiancee",
        "lover",
        "cousin",
        "uncle",
        "aunt",
        "grandma",
        "grandpa",
        "mentor",
        "student",
        "teacher",
        "apprentice",
        "boss",
        "colleague",
        "servant",
        "master",
        "neighbour",
        "neighbor",
        "king",
        "queen",
        "lord",
        "lady",
        "knight",
        "guard",
        "captain",
        "general",
    }
)

# words that look like names but aren't
FALSE_NAME_WORDS: frozenset[str] = frozenset(
    {
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
        "sunday",
        "january",
        "february",
        "march",
        "april",
        "june",
        "july",
        "august",
        "september",
        "october",
        "november",
        "december",
        "north",
        "south",
        "east",
        "west",
        "true",
        "false",
        "none",
        "null",
        "hollywood",
        "okay",
        "sorry",
        "thanks",
        "please",
        "indie",
    }
)

# location extraction stopwords
LOCATION_STOPWORDS: frozenset[str] = NAME_STOPWORDS | frozenset(
    {"not", "but", "so", "if", "then", "than", "by", "on", "up", "out"}
)

# combined deny set for fast lookup
_NAME_DENY: frozenset[str] = NAME_STOPWORDS | RELATION_WORDS | FALSE_NAME_WORDS


def is_valid_name(word: str) -> bool:
    # min 3 chars, starts uppercase, alpha only
    return (
        len(word) >= 3
        and word[0].isupper()
        and word.isalpha()
        and word.lower() not in _NAME_DENY
    )
