from __future__ import annotations

# marker tokens
LORE_MARKER = "<<<LORE_BLOCK>>>"
CHARACTERS_MARKER = "<<<CHARACTERS>>>"

# name stopwords
NAME_STOPWORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "the",
        "my",
        "your",
        "his",
        "her",
        "their",
        "our",
        "i",
        "me",
        "we",
        "you",
        "he",
        "she",
        "they",
        "it",
        "this",
        "that",
        "in",
        "at",
        "to",
        "from",
        "with",
        "for",
        "of",
        "by",
        "on",
        "and",
        "or",
        "but",
        "so",
        "if",
        "than",
        "then",
        "is",
        "was",
        "are",
        "were",
        "be",
        "been",
        "being",
        "have",
        "had",
        "do",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "here",
        "there",
        "when",
        "where",
        "what",
        "who",
        "how",
        "why",
        "old",
        "young",
        "big",
        "small",
        "new",
        "good",
        "bad",
        "just",
        "very",
        "well",
        "also",
        "back",
        "even",
        "still",
        "way",
        "look",
        "come",
        "want",
        "know",
        "think",
        "see",
        "get",
        "make",
        "said",
        "yes",
        "no",
        "not",
        "now",
        "up",
        "out",
        "okay",
        "ok",
        "hey",
        "oh",
        "ah",
        "hmm",
        "uh",
        "um",
        "never",
        "always",
        "every",
        "about",
        "after",
        "before",
        "while",
        "again",
        "away",
        "down",
        "off",
        "over",
        "under",
        "into",
        "onto",
        "much",
        "more",
        "most",
        "less",
        "least",
        "each",
        "both",
        "all",
        "any",
        "few",
    }
)

# relationship words
RELATION_WORDS: frozenset[str] = frozenset(
    {
        # personal
        "friend",
        "companion",
        "ally",
        "rival",
        "enemy",
        "brother",
        "sister",
        "sibling",
        "mother",
        "father",
        "son",
        "daughter",
        "parent",
        "child",
        "husband",
        "wife",
        "partner",
        "spouse",
        "boyfriend",
        "girlfriend",
        "fiance",
        "fiancee",
        "lover",
        "cousin",
        "uncle",
        "aunt",
        "nephew",
        "niece",
        "grandma",
        "grandpa",
        "grandmother",
        "grandfather",
        "grandchild",
        # professional
        "mentor",
        "student",
        "teacher",
        "apprentice",
        "boss",
        "colleague",
        "coworker",
        "employee",
        "employer",
        "servant",
        "master",
        # social
        "neighbour",
        "neighbor",
        "acquaintance",
        "contact",
        "associate",
        # fantasy / title
        "king",
        "queen",
        "lord",
        "lady",
        "knight",
        "guard",
        "captain",
        "general",
        "soldier",
        "spy",
        "assassin",
        "mage",
        "wizard",
        "witch",
        "hero",
        "villain",
        "chief",
        "elder",
        "oracle",
        "prince",
        "princess",
    }
)

# false name words
FALSE_NAME_WORDS: frozenset[str] = frozenset(
    {
        # days / months
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
        "sunday",
        "january",
        "february",
        "march",
        "april",
        "june",
        "july",
        "august",
        "september",
        "october",
        "november",
        "december",
        # directions
        "north",
        "south",
        "east",
        "west",
        "northeast",
        "northwest",
        "southeast",
        "southwest",
        # programming / misc tokens
        "true",
        "false",
        "none",
        "null",
        "undefined",
        "error",
        "warning",
        # common single-word exclamations/fillers that start caps
        "okay",
        "sorry",
        "thanks",
        "please",
        "indie",
        "hello",
        "welcome",
        "good",
        "right",
        "wrong",
        "wait",
        "stop",
        "help",
        "run",
        "go",
        "stay",
        "yes",
        "no",
        "well",
        "maybe",
        "perhaps",
        "indeed",
        "exactly",
        "certainly",
        # genre proper nouns that aren't character names
        "hollywood",
        "netflix",
        "amazon",
        "google",
        "microsoft",
        "apple",
        "discord",
    }
)

# combined deny set
_NAME_DENY: frozenset[str] = NAME_STOPWORDS | RELATION_WORDS | FALSE_NAME_WORDS

# location stopwords
LOCATION_STOPWORDS: frozenset[str] = NAME_STOPWORDS | frozenset(
    {
        "not",
        "but",
        "so",
        "if",
        "then",
        "than",
        "by",
        "on",
        "up",
        "out",
        "its",
        "itself",
        "himself",
        "herself",
        "themselves",
        "ourselves",
        "yourself",
    }
)


# public helpers
def is_valid_name(word: str) -> bool:
    """check if word looks like a valid name (3-30 chars, uppercase start, alpha only)"""
    return (
        3 <= len(word) <= 30
        and word[0].isupper()
        and word.isalpha()
        and word.lower() not in _NAME_DENY
    )


def normalise_name(raw: str) -> str:
    """strip punctuation and title-case a raw name token."""
    cleaned = raw.strip(".,!?;:\"'()[]{}")
    return cleaned.title() if cleaned else raw
